package postgresql.classic.constants;

public enum Instruments {
    // Strings
    VIOLIN, VIOLA, CELLO, DOUBLE_BASS, HARP,

    // Woodwinds
    FLUTE, CLARINET, BASS_CLARINET, OBOE, BASSOON, PICCOLO, RECORDER, ENGLISH_HORN,

    // Brass
    SAXOPHONE, TRUMPET, TROMBONE, FRENCH_HORN, TUBA, EUPHONIUM, CORNET, FLUGELHORN, ALTO_HORN, BARITONE_HORN,

    // Percussion
    TIMPANI, CHIMES, CYMBALS, MARIMBA, TRIANGLE, SNARE_DRUM, BASS_DRUM, GONGS,
    VIBRAPHONE, GLOCKENSPIEL, XYLOPHONE, TAMBOURINE, MARACAS, CASTANETS, CLAVES, WOOD_BLOCK, RHYTHM_STICKS,

    // Keyboard
    PIANO, ORGAN, SYNTHESIZER, HARPSICHORD, KEYBOARD,

    // Guitar
    GUITAR, BASS_GUITAR, ELECTRIC_GUITAR, BANJO, UKULELE, MANDOLIN,

    // Vocal
    TENOR, BARITONE, SOPRANO, ALTO, BASS,
}
